FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend ./backend
COPY data ./data
COPY models ./models
COPY sql ./sql
CMD ["uvicorn","backend.app.main:app","--host","0.0.0.0","--port","8000"]
